### ISSUE TITLE
Issue with test folder

### ISSUE THREAD

**Issue by andrecastelo** [tpavlek/oauth2-bnet#9]
With the testing environment set up, running `test/sc2-example.php` sends me to BattleNet and then back to the file, but with the following error:

```
Fatal error: Uncaught exception 'League\OAuth2\Client\Provider\Exception\IdentityProviderException' with message 'Internal server error' in D:\www\public\scpartners-laravel\oauth2-bnet\src\Provider\BattleNet.php:89
Stack trace: 
#0 D:\www\public\scpartners-laravel\oauth2-bnet\vendor\league\oauth2-client\src\Provider\AbstractProvider.php(620): Depotwarehouse\OAuth2\Client\Provider\BattleNet->checkResponse(Object(GuzzleHttp\Psr7\Response), Array) 
#1 D:\www\public\scpartners-laravel\oauth2-bnet\vendor\league\oauth2-client\src\Provider\AbstractProvider.php(536): League\OAuth2\Client\Provider\AbstractProvider->getResponse(Object(GuzzleHttp\Psr7\Request)) 
#2 D:\www\public\scpartners-laravel\oauth2-bnet\test\sc2-example.php(14): League\OAuth2\Client\Provider\AbstractProvider->getAccessToken('authorization_c...', Array) 
#3 {main} thrown in D:\www\public\scpartners-laravel\oauth2-bnet\src\Provider\BattleNet.php on line 89
```

**Comment by tpavlek** [comment]
This is resolved with your most recent pull, correct? Or is this different?

**Comment by andrecastelo** [comment]
This is a different one, the PR was for a minor one. If I have any success fixing this I'll submit another PR
